# .terraform-docs.yml - Configuration for terraform-docs
#
# This file configures how terraform-docs generates your README.md
# Place this in your module root and run: terraform-docs markdown . > README.md
#
# Documentation: https://terraform-docs.io/user-guide/configuration/

formatter: "markdown table"

version: ">= 0.17.0"

header-from: "docs/header.md"  # Optional: create docs/header.md for custom intro

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}

  ## Usage

  ```hcl
  module "example" {
    source  = "YOUR-USERNAME/MODULE-NAME/aws"
    version = "1.0.0"

    # Required variables
    name        = "my-resource"
    environment = "dev"

    # Optional variables (showing defaults)
    # enable_feature = true
  }
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ## Examples

  ### Basic Example

  ```hcl
  module "basic" {
    source  = "YOUR-USERNAME/MODULE-NAME/aws"
    version = "1.0.0"

    name        = "basic-resource"
    environment = "dev"
  }
  ```

  ### Advanced Example

  ```hcl
  module "advanced" {
    source  = "YOUR-USERNAME/MODULE-NAME/aws"
    version = "1.0.0"

    name        = "advanced-resource"
    environment = "prod"

    # Enable all optional features
    enable_feature = true

    tags = {
      Team    = "platform"
      Project = "infrastructure"
    }
  }
  ```

  ## License

  MIT Licensed. See [LICENSE](LICENSE) for full details.

output:
  file: "README.md"
  mode: replace

output-values:
  enabled: false

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
